@extends('admin.dashboard')

@section('page-title', 'Reports & Analytics')
@section('page-description', 'View and generate clinic reports and analytics')

@section('content')
<div class="content-header">
    <div class="header-title">
        <h1><i class="fas fa-chart-bar"></i> Reports</h1>
        <p>View and generate clinic reports and analytics</p>
    </div>
    <div class="header-actions">
        <a href="{{ route('admin.reports.create') }}" class="btn btn-primary">
            <i class="fas fa-plus"></i> Generate Report
        </a>
    </div>
</div>

<div class="card">
    <div class="card-body">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Report Type</th>
                    <th>Date</th>
                    <th>Generated By</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td colspan="5" class="text-center text-muted">No reports found</td>
                </tr>
            </tbody>
        </table>
    </div>
</div>
@endsection
