@extends('admin.dashboard')

@section('page-title', 'Report Details')
@section('page-description', 'Review report configuration')

@section('content')
<style>
    .reports-hero {
        background: linear-gradient(120deg, #f8fafc 0%, #eef2ff 60%, #fff7ed 100%);
        border: 1px solid #e2e8f0;
        border-radius: 16px;
        padding: 1.5rem 1.75rem;
        margin-bottom: 1.5rem;
    }

    .report-card {
        background: #ffffff;
        border: 1px solid #e2e8f0;
        border-radius: 16px;
        padding: 1.5rem;
        box-shadow: 0 10px 20px rgba(15, 23, 42, 0.06);
    }

    .report-meta {
        display: grid;
        grid-template-columns: repeat(auto-fit, minmax(220px, 1fr));
        gap: 1rem;
        margin-bottom: 1.25rem;
    }

    .report-meta .meta-card {
        border: 1px solid #e2e8f0;
        border-radius: 12px;
        padding: 0.85rem 1rem;
        background: #f8fafc;
    }

    .badge-status {
        padding: 0.3rem 0.7rem;
        border-radius: 999px;
        font-size: 0.75rem;
        font-weight: 600;
    }

    .badge-draft { background: #fef3c7; color: #92400e; }
    .badge-generated { background: #dcfce7; color: #166534; }
    .badge-archived { background: #e2e8f0; color: #475569; }
</style>

<div class="content-header reports-hero">
    <div class="header-title">
        <h1><i class="fas fa-file-alt"></i> Report Details</h1>
        <p>Saved configuration and quick actions</p>
    </div>
    <div class="header-actions">
        <a href="{{ route('admin.reports.index') }}" class="btn btn-outline-secondary">
            <i class="fas fa-arrow-left"></i> Back to Reports
        </a>
        <a href="{{ route('admin.reports.edit', $report) }}" class="btn btn-outline-primary">
            <i class="fas fa-pen"></i> Edit
        </a>
        <a href="{{ route('admin.reports.' . $report->report_type) }}" class="btn btn-primary">
            <i class="fas fa-play"></i> Open Report
        </a>
    </div>
</div>

<div class="report-card">
    <div class="report-meta">
        <div class="meta-card">
            <div class="text-muted small">Report Title</div>
            <div class="fw-semibold">{{ $report->title }}</div>
        </div>
        <div class="meta-card">
            <div class="text-muted small">Report Type</div>
            <div class="fw-semibold">{{ $reportTypeLabels[$report->report_type] ?? ucfirst($report->report_type) }}</div>
        </div>
        <div class="meta-card">
            <div class="text-muted small">Status</div>
            <div>
                @php
                    $status = $report->status ?? 'draft';
                    $statusClass = match ($status) {
                        'generated' => 'badge-generated',
                        'archived' => 'badge-archived',
                        default => 'badge-draft',
                    };
                @endphp
                <span class="badge-status {{ $statusClass }}">{{ ucfirst($status) }}</span>
            </div>
        </div>
        <div class="meta-card">
            <div class="text-muted small">Date Range</div>
            <div class="fw-semibold">
                {{ optional($report->start_date)->format('M d, Y') }} - {{ optional($report->end_date)->format('M d, Y') }}
            </div>
        </div>
        <div class="meta-card">
            <div class="text-muted small">Generated By</div>
            <div class="fw-semibold">{{ $report->generatedBy?->name ?? 'System' }}</div>
        </div>
        <div class="meta-card">
            <div class="text-muted small">Created</div>
            <div class="fw-semibold">{{ $report->created_at?->format('M d, Y h:i A') }}</div>
        </div>
    </div>

    <div>
        <div class="text-muted small">Notes</div>
        <div class="fw-semibold">{{ $report->notes ?: 'No notes added.' }}</div>
    </div>
</div>
@endsection
